# action.yml
name: 'Ambient Labs CI/CD Action'
description: 'Allows deployment of docker applications to the Edge using Ambient Labs CI/CD services'
inputs:
  token:
    description: 'Token for Ambient Labs CI/CD'
    required: true
  command:
    description: 'Command to execute'
    required: true
  timeout:
    description: 'Timeout for command'
    required: false
  node_ids:
    description: 'Node IDs to execute command on'
    required: false
  tags:
    description: 'Tags to execute command on'
    required: false
  store_output:
    description: 'Whether to store output'
    required: false
outputs:
  command:
    description: 'Command to execute'
  timeout:
    description: 'Timeout for command'
  node_ids:
    description: 'Node IDs to execute command on'
  tags:
    description: 'Tags to execute command on'
  store_output:
    description: 'Whether to store output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.command }}
    - ${{ inputs.timeout }}
    - ${{ inputs.node_ids }}
    - ${{ inputs.tags }}
    - ${{ inputs.store_output }}
